name: Npm Publish
on: [workflow_dispatch]
jobs:
  checkVersion:
    name: Check package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check package version
        id: check
        uses: PostHog/check-package-version@v2
        with:
          path: ./apps/editor/
      - name: Cancel when unchanged
        uses: andymckay/cancel-action@0.5
        if: steps.check.outputs.is-new-version == 'false'

  pre-check:
    needs: [checkVersion]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install
        run: |
          npm ci
      - name: Eslint
        run: |
          npm run lint:all
      - name: Check types
        run: |
          npm run test:types:all

  test:
    needs: [checkVersion]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install
        run: |
          npm ci
      - name: Build
        run: |
          npm run build toastmark
      - name: Toastmark unit, integration test
        run: |
          npm run test:ci toastmark
      - name: Editor unit, integration test
        run: |
          npm run test:ci editor

  plugin-test:
    needs: [checkVersion]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install
        run: |
          npm ci
      - name: Build
        run: |
          npm run build toastmark
          npm run build editor
      - name: chart plugin unit, integration test
        run: |
          npm run test:ci chart
      - name: color syntax plugin unit, integration test
        run: |
          npm run test:ci color
      - name: code syntax highlighting plugin unit, integration test
        run: |
          npm run test:ci code
      - name: table merged cell plugin unit, integration test
        run: |
          npm run test:ci table
      - name: uml plugin unit, integration test
        run: |
          npm run test:ci uml

  publish:
    permissions:
      actions: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    needs: [pre-check, test, plugin-test]
    steps:
      - uses: actions/checkout@v6
      - name: Check the package version
        id: check
        uses: PostHog/check-package-version@v2
        with:
          path: ./apps/editor/
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: |
          npm ci
      - name: Build packages
        run: |
          items=(
            "toastmark"
            "editor"
            "react"
            "vue"
            "chart"
            "color"
            "code"
            "table"
            "uml"
          )
          for item in "${items[@]}"; do
            npm run build ${item}
          done
      - name: Generate Github Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: v${{ steps.check.outputs.committed-version }}
      - name: Npm Publish
        run: |
          items=(
            "./apps/editor"
            "./apps/react-editor"
            "./apps/vue-editor"
            "./plugins/chart"
            "./plugins/code-syntax-highlight"
            "./plugins/color-syntax"
            "./plugins/table-merged-cell"
            "./plugins/uml"
          )
          for item in "${items[@]}"; do
            cd ${item}
            npm publish --provenance --access public
            cd -
          done
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
